### ISSUE TITLE
Phoenix.rebirth not working on Flutter web

### ISSUE THREAD

**Issue by chengboonrong** [The-ring-io/flutter_phoenix#16]
I have been testing on local network and also https protocol network, but it didn't work.
And I can't find any references for Flutter web development. Not sure it is still an early development stage for Flutter web

Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:3000/dart_sdk.js:5348:11)
    at Object.nullCheck (http://localhost:3000/dart_sdk.js:5681:30)
    at Function.rebirth (http://localhost:3000/packages/flutter_phoenix/flutter_phoenix.dart.lib.js:72:12)
    at http://localhost:3000/packages/aliments_v2/screens/splash/splash_screen_page.dart.lib.js:83169:41
    at Generator.next (<anonymous>)
    at http://localhost:3000/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:3000/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:3000/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:3000/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:3000/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:3000/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:3000/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:3000/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:3000/dart_sdk.js:39380:13)
    at http://localhost:3000/dart_sdk.js:34887:9

**Comment by mariusCristianPop** [comment]
Same for me. I tested it in a web browser and it does not work.

**Comment by CallMeSH** [comment]
Hello,

As of today, this plugin has not been tested on Flutter Web and we have no idea if it is compatible or not.
Sorry that we can't help with it for now.

**Comment by mmazurovsky** [comment]
@CallMeSH could you please delete 'web' marker [here](https://pub.dev/packages/flutter_phoenix) if it is not tested?

**Comment by kenNg1** [comment]
@chengboonrong @mmazurovsky  it seems to work on web if you do the below:

If you save navigator state in a global key such as `GlobalKey<NavigatorState>` and do `await Phoenix.rebirth(navigatorKey.currentState!.context)`, it seems to work on web (at least on my side).

FYI. I am also using `auto-route` library and `get_it` but have excluded it from the above code in case you don't use it.

**Comment by vipafattal** [comment]
> Future<void> _navigateAndReset() async {
>     final stackData = s<Nav>().stackData;
> 
>     if (stackData
>         .where((element) => element.name == AuthRoute.name)
>         .isNotEmpty) {
>       s<Nav>().popUntil((route) => route.isFirst); // if you came from the root route
>     } else {
>       await s<Nav>().popAndPush(const AuthRoute()); // if you did not come from the root route
>     }
> 
>     await Phoenix.rebirth(s<Nav>().navigatorKey.currentState?.context);
>   }

I am using the same tech stack mind sharing full sample

**Comment by Miiite** [comment]
The unsupported platforms were removed from the `pub.dev` page for clarity. Closing this issue.
